baseURL = "https://sammy-ashford.github.io/"
languageCode = "en-us"
title = "Sam Ashford"
theme = "sam"

[params]
  author = "Sam Ashford"
  description = "Thoughts from Fox Point. Things I keep returning to."
